[build]
  publish = "public"
  command = "echo 'No build required'"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/models/*"
  to = "/.netlify/functions/gemini-proxy/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
